// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://ucfchqacuzykirsxonzl.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjZmNocWFjdXp5a2lyc3hvbnpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzEwMjI4MTcsImV4cCI6MjA0NjU5ODgxN30.gewq2lteu8eKvcQIZB4NwpKWBousnsCdzQWLvfhKsA0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);